### ISSUE TITLE
Missing checkpoint, reproducing results

### ISSUE THREAD

**Issue by t-kuculo** [pldlgb/MetaSD#1]
Hi. I have a question. It seems that the code depends on an existence of a model checkpoint that was not made available. When I make the appropriate adjustments for the lack of this checkpoint the results are considerably lower than those in the paper. Could you provide the missing checkpoint?

**Comment by pldlgb** [comment]
CUDA_VISIBLE_DEVICES=3 python metasd.py --dataset FB237 --batch_size 5000 --reg 5e-2 --prune_percent 0.9 --use_relaux True -train -save -id test

**Comment by t-kuculo** [comment]
Thank you for the reply. 

Running the script you have given me results in the following output:

MRR: 0.0008596231346018612
hits@[1,3,10]: [0.00012215381138958037, 0.00036646146327257156, 0.0010993843898177147]

Is there a way of reproducing results from the paper?

**Comment by pldlgb** [comment]
Perhaps you can try downloading the data from this repository. I don't know what dataset you are using. `https://github.com/MIRALab-USTC/KGE-DURA`
You can star our project to keep track of our future updates.
